-- 1. Tabela de Clientes
CREATE TABLE IF NOT EXISTS clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT CHECK (type IN ('PF', 'PJ')),
    document TEXT,
    email TEXT,
    phone TEXT,
    cep TEXT,
    rua TEXT,
    numero TEXT,
    bairro TEXT,
    cidade TEXT,
    estado TEXT,
    complemento TEXT,
    sync_status TEXT DEFAULT 'synced',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabela de Colaboradores
CREATE TABLE IF NOT EXISTS collaborators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT,
    status TEXT DEFAULT 'Ativo',
    email TEXT,
    phone TEXT,
    sync_status TEXT DEFAULT 'synced',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabela de Maquinário
CREATE TABLE IF NOT EXISTS machinery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    model TEXT,
    serial_number TEXT,
    client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
    instalacao TEXT,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'maintenance', 'inactive')),
    sync_status TEXT DEFAULT 'synced',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabela de Tipos de Serviço
CREATE TABLE IF NOT EXISTS service_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    sync_status TEXT DEFAULT 'synced',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabela de Serviços (Ordens de Serviço)
CREATE TABLE IF NOT EXISTS services (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT,
    date TIMESTAMPTZ DEFAULT NOW(),
    client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
    machine_id BIGINT REFERENCES machinery(id) ON DELETE SET NULL,
    technician_id BIGINT REFERENCES collaborators(id) ON DELETE SET NULL,
    service_type_id BIGINT REFERENCES service_types(id) ON DELETE SET NULL,
    valor DECIMAL(12,2) DEFAULT 0,
    valor_hh DECIMAL(12,2) DEFAULT 0,
    status TEXT DEFAULT 'pending',
    duration TEXT,
    area TEXT,
    sync_status TEXT DEFAULT 'synced',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Índices para Otimização de Busca
CREATE INDEX IF NOT EXISTS idx_services_id ON services(id);
CREATE INDEX IF NOT EXISTS idx_services_client ON services(client_id);
CREATE INDEX IF NOT EXISTS idx_services_machine ON services(machine_id);
CREATE INDEX IF NOT EXISTS idx_machinery_client ON machinery(client_id);

-- 7. Triggers para atualizar o updated_at automaticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_clients_updated_at ON clients;
CREATE TRIGGER update_clients_updated_at BEFORE UPDATE ON clients FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_collaborators_updated_at ON collaborators;
CREATE TRIGGER update_collaborators_updated_at BEFORE UPDATE ON collaborators FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_machinery_updated_at ON machinery;
CREATE TRIGGER update_machinery_updated_at BEFORE UPDATE ON machinery FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_services_updated_at ON services;
CREATE TRIGGER update_services_updated_at BEFORE UPDATE ON services FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
-- 9. Funções de Sincronização RPC (Batch Sync)

-- Sincronizar Clientes
CREATE OR REPLACE FUNCTION sync_clients(p_clients JSONB)
RETURNS VOID AS $$
BEGIN
    INSERT INTO clients (
        id, name, type, document, email, phone, cep, rua, numero, bairro, cidade, estado, complemento, created_at, updated_at
    )
    SELECT 
        (x->>'id')::BIGINT,
        (x->>'name'),
        (x->>'type'),
        (x->>'document'),
        (x->>'email'),
        (x->>'phone'),
        (x->>'cep'),
        (x->>'rua'),
        (x->>'numero'),
        (x->>'bairro'),
        (x->>'cidade'),
        (x->>'estado'),
        (x->>'complemento'),
        COALESCE((x->>'created_at')::TIMESTAMPTZ, NOW()),
        NOW()
    FROM jsonb_array_elements(p_clients) AS x
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        type = EXCLUDED.type,
        document = EXCLUDED.document,
        email = EXCLUDED.email,
        phone = EXCLUDED.phone,
        cep = EXCLUDED.cep,
        rua = EXCLUDED.rua,
        numero = EXCLUDED.numero,
        bairro = EXCLUDED.bairro,
        cidade = EXCLUDED.cidade,
        estado = EXCLUDED.estado,
        complemento = EXCLUDED.complemento,
        updated_at = NOW();
END;
$$ LANGUAGE plpgsql;

-- Sincronizar Maquinário
CREATE OR REPLACE FUNCTION sync_machinery(p_machinery JSONB)
RETURNS VOID AS $$
BEGIN
    INSERT INTO machinery (
        id, name, model, serial_number, client_id, instalacao, status, created_at, updated_at
    )
    SELECT 
        (x->>'id')::BIGINT,
        (x->>'name'),
        (x->>'model'),
        (x->>'serial_number'),
        (x->>'client_id')::BIGINT,
        (x->>'instalacao'),
        (x->>'status'),
        COALESCE((x->>'created_at')::TIMESTAMPTZ, NOW()),
        NOW()
    FROM jsonb_array_elements(p_machinery) AS x
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        model = EXCLUDED.model,
        serial_number = EXCLUDED.serial_number,
        client_id = EXCLUDED.client_id,
        instalacao = EXCLUDED.instalacao,
        status = EXCLUDED.status,
        updated_at = NOW();
END;
$$ LANGUAGE plpgsql;

-- Sincronizar Colaboradores
CREATE OR REPLACE FUNCTION sync_collaborators(p_collaborators JSONB)
RETURNS VOID AS $$
BEGIN
    INSERT INTO collaborators (
        id, name, role, status, email, phone, created_at, updated_at
    )
    SELECT 
        (x->>'id')::BIGINT,
        (x->>'name'),
        (x->>'role'),
        (x->>'status'),
        (x->>'email'),
        (x->>'phone'),
        COALESCE((x->>'created_at')::TIMESTAMPTZ, NOW()),
        NOW()
    FROM jsonb_array_elements(p_collaborators) AS x
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        role = EXCLUDED.role,
        status = EXCLUDED.status,
        email = EXCLUDED.email,
        phone = EXCLUDED.phone,
        updated_at = NOW();
END;
$$ LANGUAGE plpgsql;

-- Sincronizar Serviços (Ordens de Serviço)
CREATE OR REPLACE FUNCTION sync_services(p_services JSONB)
RETURNS VOID AS $$
BEGIN
    INSERT INTO services (
        id, title, date, client_id, machine_id, technician_id, service_type_id, valor, valor_hh, status, duration, area, created_at, updated_at
    )
    SELECT 
        (x->>'id')::UUID,
        (x->>'title'),
        (x->>'date')::TIMESTAMPTZ,
        NULLIF(x->>'client_id', '')::BIGINT,
        NULLIF(x->>'machine_id', '')::BIGINT,
        NULLIF(x->>'technician_id', '')::BIGINT,
        NULLIF(x->>'service_type_id', '')::BIGINT,
        NULLIF(x->>'valor', '')::DECIMAL,
        NULLIF(x->>'valor_hh', '')::DECIMAL,
        (x->>'status'),
        (x->>'duration'),
        (x->>'area'),
        COALESCE((x->>'created_at')::TIMESTAMPTZ, NOW()),
        NOW()
    FROM jsonb_array_elements(p_services) AS x
    ON CONFLICT (id) DO UPDATE SET
        title = EXCLUDED.title,
        date = EXCLUDED.date,
        client_id = EXCLUDED.client_id,
        machine_id = EXCLUDED.machine_id,
        technician_id = EXCLUDED.technician_id,
        service_type_id = EXCLUDED.service_type_id,
        valor = EXCLUDED.valor,
        valor_hh = EXCLUDED.valor_hh,
        status = EXCLUDED.status,
        duration = EXCLUDED.duration,
        area = EXCLUDED.area,
        updated_at = NOW();
END;
$$ LANGUAGE plpgsql;

-- Sincronizar Tipos de Serviço
CREATE OR REPLACE FUNCTION sync_service_types(p_types JSONB)
RETURNS VOID AS $$
BEGIN
    INSERT INTO service_types (id, name, created_at)
    SELECT 
        (x->>'id')::BIGINT,
        (x->>'name'),
        COALESCE((x->>'created_at')::TIMESTAMPTZ, NOW())
    FROM jsonb_array_elements(p_types) AS x
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name;
END;
$$ LANGUAGE plpgsql;

-- 10. Tabela de Perfis de Usuário (vinculada ao Auth do Supabase)
CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT,
    email TEXT,
    avatar_url TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS nos perfis
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Usuários podem ver seu próprio perfil" 
ON profiles FOR SELECT 
USING (auth.uid() = id);

CREATE POLICY "Usuários podem atualizar seu próprio perfil" 
ON profiles FOR UPDATE 
USING (auth.uid() = id);

-- Trigger para criar perfil automaticamente no SignUp
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, full_name, email)
    VALUES (
        NEW.id, 
        COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.email), 
        NEW.email
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- 11. Políticas de Segurança (Row Level Security - RLS)

-- Habilitar RLS nas tabelas operacionais
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE collaborators ENABLE ROW LEVEL SECURITY;
ALTER TABLE machinery ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;

-- Criar políticas para permitir acesso total a usuários autenticados

-- Clientes
CREATE POLICY "Acesso total p/ autenticados" ON clients FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Colaboradores
CREATE POLICY "Acesso total p/ autenticados" ON collaborators FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Maquinário
CREATE POLICY "Acesso total p/ autenticados" ON machinery FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Tipos de Serviço
CREATE POLICY "Acesso total p/ autenticados" ON service_types FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Serviços (Ordens de Serviço)
CREATE POLICY "Acesso total p/ autenticados" ON services FOR ALL TO authenticated USING (true) WITH CHECK (true);
